In [4]:
import pickle

In [12]:
len("KALTARQQEVFDLIRDHISQTGMPPTRAEIAQRLGFRSPNAAEEHLKALARKGVIEIVSGASRGIRLLQEE")

71

In [23]:
import torch
import os
from esm import Alphabet, FastaBatchedDataset, ProteinBertModel
os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [24]:
model, alphabet = torch.hub.load("facebookresearch/esm", "esm1_t34_670M_UR50S")

Using cache found in /home/sandra/.cache/torch/hub/facebookresearch_esm_main


ImportError: cannot import name 'esmfold_structure_module_only_8M' from 'esm.pretrained' (/home/sandra/miniconda3/envs/LASTCHANCETF/lib/python3.9/site-packages/esm/pretrained.py)

In [6]:
batch_converter = alphabet.get_batch_converter()
data = [("protein1", "MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG")]
batch_labels, batch_strs, batch_tokens = batch_converter(data)
with torch.no_grad():
    results = model(batch_tokens.to(device="cpu"), repr_layers=[33], return_contacts=False)

In [9]:
import numpy as np
list(np.mean(results['representations'][33].numpy(), axis = 1)[0])

[0.4844969,
 -0.6427923,
 -1.2017659,
 0.115522064,
 0.20792872,
 -0.0654807,
 0.76893914,
 1.1665244,
 0.037317272,
 -0.16552676,
 1.170787,
 0.18362778,
 0.18510304,
 0.77762616,
 0.8901563,
 -0.8712372,
 -0.013260183,
 -0.9097673,
 0.8952208,
 -0.6600153,
 0.32974216,
 0.8839369,
 -0.09080185,
 -0.33702725,
 -0.26045313,
 0.47590616,
 -0.0033461398,
 -1.0002494,
 0.20440885,
 -0.96347135,
 1.0191416,
 -0.23677395,
 -0.6485693,
 -0.679699,
 0.19127227,
 0.18774602,
 -0.5450124,
 0.1766116,
 -0.07853865,
 -0.20675744,
 -0.6988071,
 -0.85530436,
 0.79036754,
 0.16481385,
 -0.19912204,
 -0.58730674,
 0.6569166,
 -1.6526743e-05,
 -0.16941972,
 0.035054926,
 -0.8373661,
 -0.27448124,
 -0.51294786,
 -1.2324957,
 0.92030627,
 -0.47463188,
 1.0852416,
 -0.09254624,
 0.24256507,
 -1.135995,
 -1.5927784,
 0.45437428,
 0.42498595,
 0.08601322,
 0.041051876,
 0.3422928,
 1.4978364,
 -0.6128791,
 -0.044636033,
 0.07769287,
 0.30758592,
 1.671213,
 0.636547,
 1.2650248,
 1.0387772,
 0.6393618,
 0.

In [10]:
arr = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

arr[0,0,0:-1]

array([1, 2])

In [26]:
[list(i) for i in np.mean(arr, axis=1)]

[[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]]

In [39]:
string = "".join([f" {i}" for i in "MKVTIVGAGNVGATCADVISYRGIASEVVLLDIKEGFAEGKAMDIMQCATTTGFNTKVSGVTNDYSKTANSDVVVITSGIPRKPGMTREELIGINAGIVKSVAENILKFSPNTIIVVVSNPMDTMTYLTLKATGLPKNRII"])[1:]

In [40]:
string

'M K V T I V G A G N V G A T C A D V I S Y R G I A S E V V L L D I K E G F A E G K A M D I M Q C A T T T G F N T K V S G V T N D Y S K T A N S D V V V I T S G I P R K P G M T R E E L I G I N A G I V K S V A E N I L K F S P N T I I V V V S N P M D T M T Y L T L K A T G L P K N R I I'

In [31]:
import pickle
with open("../results/Embeddings/test3.pkl", 'rb') as f:
    df = pickle.load(f)

In [32]:
np.all(df["Embedding"][0] == df["Embedding"][1])

False

In [33]:
len(df["Embedding"][0])

1280

In [3]:
import numpy as np

In [4]:
arr0 = np.array([-0.0927695,   0.085255,    0.06334297,  0.11610556,  0.07751884])
arr1 = np.array([ 0.09757023,  0.00109583,  0.15822381,  0.18456812, -0.00931343])
arr2 = np.array([ 0.01525027, -0.11829904,  0.13254347,  0.23841138, -0.04198679])
arr3 = np.array([-0.04112213, -0.17652196, -0.0082274,   0.13943122, -0.01274696])
arr4 = np.array([-0.00526778, -0.05211754,  0.08647071,  0.16962907,  0.00336791])

In [5]:
arr_sum = arr0 + arr1 + arr2 + arr3

In [6]:
print(arr_sum)

[-0.02107113 -0.20847017  0.34588285  0.67851628  0.01347166]


In [7]:
print(arr_sum/4)

[-0.00526778 -0.05211754  0.08647071  0.16962907  0.00336792]
